[
    {
        "participante": "Iris Rocha Campos",
        "nomeNegocio": "B.Girl",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Gabriela Serpa",
        "estagio": "Oficialmente lançado",
        "eMail": "iriscampos@me.com",
        "celular": "11971272027",
        "cidadeEstado": "São Paulo -SP",
        "linkedin": "https://www.linkedin.com/in/iris-rocha-45a986125/",
        "instagramPessoal": "https://www.instagram.com/iris.rocha.campos/",
        "siteDaEmpresa": "https://www.instagram.com/b.girl_brasil/",
        "redesSociaisEmpresa": "https://bgirlbrasil.com.br/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Uma adtech especializada em comunicação com as adolescentes das novas gerações, que cria desafios online para promover mídia espontânea nas redes sociais para marcas ao mesmo tempo que as auxilia na sua fixação como agente transformador, gerando impacto nessa comunidade, através do desenvolvimento de soft skills e da auto estima positiva"
    },
    {
        "Participante": "Natália Titos",
        "nomeNegocio": "B.Girl",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Gabriela Serpa",
        "estagio": "Oficialmente lançado",
        "eMail": "nataliattitos@gmail.com",
        "celular": "11976275135",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/natalia-titos-21064b2b/",
        "instagramPessoal": "https://www.instagram.com/nataliatitos/",
        "siteDaEmpresa": "https://bgirlbrasil.com.br/",
        "redesSociaisEmpresa": "Não localizado",
        "segmentoDaEmpresa": "Moda",
        "descricaoNegocio": "Uma adtech especializada em comunicação com as adolescentes das novas gerações, que cria desafios online para promover mídia espontânea nas redes sociais para marcas ao mesmo tempo que as auxilia na sua fixação como agente transformador, gerando impacto nessa comunidade, através do desenvolvimento de soft skills e da auto estima positiva"
    },
    {
        "Participante": "Anna Giselli Barboza Carneiro Martínez",
        "nomeNegocio": "BabyThings.Rent",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Aline Saito",
        "estagio": "Protótipo/Versão beta",
        "eMail": "gisellimartinez@gmail.com",
        "celular": "92984155537",
        "cidadeEstado": "Manaus - AM",
        "linkedin": "https://www.linkedin.com/in/giselli-mart%C3%ADnez-97a32a178/",
        "instagramPessoal": "https://www.instagram.com/gisellimartinez/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/babythings.rent/",
        "segmentoDaEmpresa": "Acessórios para gestantes e maternidade",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Plataforma de aluguel de itens para bebês e crianças com curto prazo de usabilidade, mas que sejam práticos e compactos para quem viaja ou recebe crianças em casa."
    },
    {
        "Participante": "Anna Beatriz Vieira dos Santos ",
        "nomeNegocio": "Base Sustentabilidade ",
        "checkPonit_1": "OK",
        "Mentora": "Rafaela Bassetti",
        "estagio": "Protótipo/Versão beta",
        "eMail": "annabeatrizvs@gmail.com",
        "celular": "11995984625",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "http://linkedin.com/in/anna-beatriz-dos-santos-lira-8b2802166 ",
        "instagramPessoal": "https://www.instagram.com/eai_biba/",
        "siteDaEmpresa": "www.basesustentabilidade.org",
        "redesSociaisEmpresa": "https://www.instagram.com/basesustentabilidade/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Setor 2,5 - sustentabilidade e tecnólogo ",
        "descricaoNegocio": "A Base Sustentabilidade é um Guia de Consumo Consciente. Usamos de crowdsouring para avaliar os produtos e estabelecimentos através do tripé da sustentabilidade. Instruímos também nossa comunidade com conteúdos provocativos em nossa mídias sociais, com a missão de despertar mentes para seus hábitos e consumos. Queremos conectar as pessoas que querem consumir melhor com as marcas e empresas que tem o cuidado com o meio ambiente. Nosso próximo passo é desenvolver nosso Market place para facilitar o acesso da nossa comunidade aos produtos sustentáveis, mas nossa visão vai além, queremos ser “one stop shop” da sustentabilidade e comercializar tudo que a nossa comunidade precisa: alimentos, turismo, educação ... tudo!  Hoje já influenciamos mais de 14k nas nossas redes sociais, principalmente no Instagram e nosso canal no YouTube."
    },
    {
        "Participante": "Sofia Quadros Affonseca",
        "nomeNegocio": "Binni",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Cecilia Gomes",
        "estagio": "Protótipo/Versão beta",
        "eMail": "sofiaqaffonseca@gmail.com",
        "celular": "21986571010",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/sofia-affonseca-20219998/",
        "instagramPessoal": "https://www.instagram.com/sofiaqaffonseca/",
        "siteDaEmpresa": "https://www.behance.net/gallery/56306517/Binni",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Saúde e bem-estar",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "É uma linha interativa de brinquedos para crianças com autismo composta por dois produtos _nhac: mordedor que vibra ao apertar. Acalma, diminui a ansiedade e o estresse _modulando: tapete composto por módulos hexagonais que acendem ao pisar. Atuam no foco, equilíbrio e mapeamento visual Foi uma forma que encontrei de ajudar a desenvolver todo seu potencial e melhorar a qualidade de vida. "
    },
    {
        "Participante": "Alexandra Romana",
        "nomeNegocio": "Camadas",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Aline Saito",
        "estagio": "Ideia",
        "eMail": "ale.camadas@gmail.com",
        "celular": "2198348-6409",
        "cidadeEstado": "Rio de Janeiro - RJ",
        "linkedin": "https://www.linkedin.com/in/alexandra-romana-013a5917a/",
        "instagramPessoal": "https://www.instagram.com/aleromanas/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/soucamadas/",
        "segmentoDaEmpresa": "Saúde e bem-estar",
        "descricaoNegocio": "Conecta profissionais da beleza a espaços | salões ociossos."
    },
    {
        "Participante": "Juliana Freitas Lopes de Souza",
        "nomeNegocio": "ComPor",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Viviane Nagao",
        "estagio": "Ideia",
        "eMail": "juflopes@gmail.com",
        "celular": "11989251165",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/juliana-freitas-lopes-de-souza-76146bb5/",
        "instagramPessoal": "https://www.instagram.com/comporeventos/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/compor_s2/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Aplicativo que auxilia pessoas sem experiência a realizar seu Evento, seria uma Assessoria Digital. "
    },
    {
        "Participante": "Rosyane Maria Silva",
        "nomeNegocio": "Compre de uma mãe preta",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Amanda Graciano",
        "estagio": "Protótipo/Versão beta",
        "eMail": "rosysilwa2@gmail.com",
        "celular": "11982549173",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "Não possui",
        "instagramPessoal": "https://www.instagram.com/perolas_di_maria/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/compredeumamaepreta/",
        "segmentoDaEmpresa": "Economia criativa (publicidade, redes sociais)",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Divulgação e vendas de produtos e serviços de MÃES NEGRAS (PRETAS E PARDAS), MÃES AFRO-INDÍGENAS , INDÍGENAS e IMIGRANTES NEGRAS. "
    },
    {
        "Participante": "Tuanny Miler",
        "nomeNegocio": "Compre de uma mãe preta",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Amanda Graciano",
        "estagio": "Protótipo/Versão beta",
        "eMail": "tuannymiller.anga@gmail.com",
        "celular": "16994504863",
        "cidadeEstado": "Ribeirão Preto - SP",
        "linkedin": "https://www.linkedin.com/in/tuanny-miller-silva-43315617a/",
        "instagramPessoal": "https://www.instagram.com/tuanny_millermaternidadepreta/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/compredeumamaepreta/",
        "segmentoDaEmpresa": "Economia criativa (publicidade, redes sociais)",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Divulgação e vendas de produtos e serviços de MÃES NEGRAS (PRETAS E PARDAS), MÃES AFRO-INDÍGENAS , INDÍGENAS e IMIGRANTES NEGRAS. "
    },
    {
        "Participante": "Bianca Kirschner",
        "nomeNegocio": "Conexão Alimentar",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Thais Vasconcellos",
        "estagio": "Oficialmente lançado",
        "eMail": "conexaoalimentarbr@gmail.com",
        "celular": "11989212696",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/bianca-kirschner-4827b247/",
        "instagramPessoal": "https://www.instagram.com/biakirschner/",
        "siteDaEmpresa": "https://conexaoalimentar.com.br/",
        "redesSociaisEmpresa": "https://www.instagram.com/conexaoalimentaroficial/",
        "segmentoDaEmpresa": "Saúde e bem-estar",
        "tipoNegocio": "Terceiro Setor",
        "descricaoNegocio": "O Conexão Alimentar surgiu como uma alternativa para conectar interessados no tema alergia alimentar por meio de conteúdos de credibilidade e ações criativas, bem como, incentivar a troca de experiências e disseminar conhecimento. Dessa forma, o portal tem como objetivo apoiar portadores de alergias alimentares e seus familiares e também quem já está desenvolvendo ações dentro dessa comunidade. Ainda sem números exatos, no Brasil e no Mundo, milhões de pessoas refletem essa condição de alérgicos. O conhecimento, mais do que nunca, pode fazer a diferença em ter ou não uma vida completa. Por último, também desejamos através do portal educar a comunidade não alérgica, pois as escolas, os restaurantes e os hospitais, ou seja, a comunidade em geral, também precisa se preparar para aumentar a inclusão dessa comunidade que cresce."
    },
    {
        "Participante": "Patrícia Campos Antonino",
        "nomeNegocio": "Connectholics ",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Jaqueline Lamente",
        "estagio": "Ideia",
        "eMail": "patricia.antonino@gmail.com",
        "celular": "11960641464",
        "cidadeEstado": "Salvador - BA",
        "linkedin": "https://www.linkedin.com/in/patr%C3%ADcia-antonino-87296659/",
        "instagramPessoal": "https://www.instagram.com/patricia.antonino/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/connectholics/",
        "segmentoDaEmpresa": "Economia criativa (publicidade, redes sociais)",
        "tipoNegocio": "Comunidade + serviços ",
        "descricaoNegocio": "Em um cenário de incertezas e falta de perspectivas, surge a Connectholics, com o objetivo de conectar pessoas, empresas e tecnologias para potencializar as suas possibilidades de atuação e resultados. A Connectholics será uma plataforma web responsiva composta por três pilares: conexões humanas, conexões empresariais e conexões tecnológicas. Uma comunidade de pessoas onde o único pré-requisito é o desejo de conectar consigo mesmo, com os outros, com as tecnologias e com o mundo, para fazer deste um lugar melhor."
    },
    {
        "Participante": "Raissa Beltrão Vasconcelos",
        "nomeNegocio": "Cria Mundo",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Betina Araujo",
        "estagio": "Protótipo/Versão beta",
        "eMail": "raissavasconcelos007@gmail.com",
        "celular": "81988785180",
        "cidadeEstado": "Recife - PE",
        "linkedin": "https://www.linkedin.com/in/raissa-vasconcelos-aab4871a9/",
        "instagramPessoal": "https://www.instagram.com/raissabvasconcelos/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Acessórios para gestantes e maternidade",
        "tipoNegocio": "Marketplace Online",
        "descricaoNegocio": "Será uma plataforma digital de marketplace C2C voltado para maternidade, consumo consciente e empreendedorismo. Terá 2 viés. 1- compra e venda de produtos semi-novos infantis. Valores como sustentabilidade e economia circular estarão presentes. 2- espaço para expor e vender os produtos manuais de mães empreendedoras. Ambos serão mães. Um compra e venda e produtos semi-novos e no outro espaço de incentivo ao empreendedorismo materno"
    },
    {
        "Participante": "Kelly Damasceno",
        "nomeNegocio": "Dellipet",
        "mentoriaPerformance": "Pendente",
        "checkPonit_1": "OK",
        "Mentora": "Valéria Nakamura",
        "estagio": "Lançado com tração e clientes",
        "eMail": "kellycristinn@gmail.com",
        "celular": "21981296209",
        "cidadeEstado": "Rio de Janeiro",
        "linkedin": "https://www.linkedin.com/in/kelly-cristina-damasceno-91444810a/",
        "instagramPessoal": "Não possui",
        "siteDaEmpresa": "https://www.dellipet.com.br/",
        "redesSociaisEmpresa": "https://www.instagram.com/dellipet/",
        "segmentoDaEmpresa": "Alimentos e bebidas",
        "descricaoNegocio": "Alimentação 100% naturtal para gatos e cachorros."
    },
    {
        "Participante": "Talita Barone",
        "nomeNegocio": "eBUFFET",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Lais Rume",
        "estagio": "Protótipo/Versão beta",
        "eMail": "ebuffetcom@gmail.com",
        "celular": "19993498079",
        "cidadeEstado": "Valinhos - SP",
        "linkedin": "https://www.linkedin.com/in/talita-barone-38260b46/",
        "instagramPessoal": "https://www.instagram.com/talita.barone/",
        "siteDaEmpresa": "www.e-buffet.com",
        "redesSociaisEmpresa": "https://www.instagram.com/ebuffetcom/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "O eBUFFET é uma startup de festa infantil tendo como modelo de negocio o marketplace, propomos uma nova maneira de realizar vendas e de apresentar  buffets e cardápios as mães que buscam festa infantil - tudo online e com geolocalização, permitindo o mapeamento dos buffets mais próximos ao endereço dos clientes."
    },
    {
        "Participante": "Marina Meirelles Ratton",
        "nomeNegocio": "Feel",
        "mentoriaPerformance": "OK",
        "Mentora": "Betina Araujo",
        "estagio": "Oficialmente lançado",
        "eMail": "maratton@gmail.com",
        "celular": "11983526084",
        "cidadeEstado": "Jundiaí - SP",
        "linkedin": "https://www.linkedin.com/in/marinarattonmarketing/",
        "instagramPessoal": "https://www.instagram.com/maratton/",
        "siteDaEmpresa": "https://www.feellube.com.br/",
        "redesSociaisEmpresa": "https://www.instagram.com/feel.lube/",
        "segmentoDaEmpresa": "Saúde e bem-estar",
        "tipoNegocio": "Comércio",
        "descricaoNegocio": "A feel é uma marca de cosméticos íntimos exclusiva para mulheres e dentro do conceito \"vagina friendly\". Nosso propósito é ajudar mulheres a se conectarem com sua intimidade através de produtos naturais e limpos, com pouco ou nenhum componente agressivo à vagina e a vulva. O mix de produto inicial é: lubrificante íntimo à base de aloe vera e 80% natural, sabonete íntimo regulador do ph e 70% natural, e um óleo calmante e também natural que pode ser usado em vários momentos (pós relação sexual, período menstrual ou até mesmo durante a menopausa). Todos os produtos não possuem essências ou insumos agressores, prezando o cuidado com nossa região íntima. A marca tem uma estratégia de nascer como nativa digital, ou seja, apostamos em conteúdo, pesquisa, levantamento de dados e fortalecimento de comunidade para posteriormente lançar o mix inicial descrito acima. É uma marca jovem, orientada aos propósitos da nova geração de mulheres mas com grandes ambições no futuro: uso de novos insumos como cdb, preservativos com pouca ou nenhuma química e formulações exclusivas a partir de informações de clientes. Estamos em uma fase de aprovação das formulações citadas acima e um programa de aceleração nos ajudaria a refinar o modelo de negócio, reforçar a estratégia de escala e nos deixar aptas para receber investimentos. Reforçamos que nossa empresa é composta de mulheres e para mulheres. Uma femtech com sólidos propósitos. "
    },
    {
        "Participante": "Renata da Silva Lima",
        "nomeNegocio": "Flow",
        "checkPonit_1": "OK",
        "Mentora": "Mariana Hagel",
        "estagio": "Ideia",
        "eMail": "rslima60@gmail.com",
        "celular": "11998801606",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/renata-lima-957514156/",
        "instagramPessoal": "Não localizado",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Saúde e bem-estar",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Será um aplicativo para ajudar a pessoa a ser sua mehor versão. A idéia é ter uma equipe de parceiros multidiciplinar nas areas de nutrição e qualidade de vida que montará os planos personalizados baseados no mapeamento genético do usuário, entre outros."
    },
    {
        "Participante": "Bruna Ribas Ruus",
        "nomeNegocio": "Geocriativa",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Gabriela Serpa",
        "estagio": "Ideia",
        "eMail": "bruna.russ@gmail.com",
        "celular": "4192350664",
        "cidadeEstado": "Curitiba - PR",
        "linkedin": "https://www.linkedin.com/in/bruna-ribas-russ-79684857/",
        "instagramPessoal": "https://www.instagram.com/brunaribasruss/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "A Geocriativa Planeta Próspero tem a missão de criar um \"marketplace\" de serviços ambientais e educacionais, sistematizados em uma plataforma online. A plataforma irá unir os serviços de cadastramento nacional de profissionais, busca por fornecedores de serviços ambientais tais como adequação ambiental de propriedades, design sustentável, conservação ambiental entre outros, além de servir de hospedagem para cursos online e plataforma de financiamento coletivo para projetos de conservação e regeneração ambiental socioambiental."
    },
    {
        "Participante": "Mariana da Silva Oliveira Campos",
        "nomeNegocio": "Governance Tree",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Maria Carolina Santos ",
        "estagio": "Focado em ganhar escala",
        "eMail": "governance.startup@gmail.com",
        "celular": "11981618718",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/mariana-oliveira-campos-49156629/",
        "instagramPessoal": "https://www.instagram.com/maricotaoliva/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/governance_tree/",
        "segmentoDaEmpresa": "Tecnologia",
        "descricaoNegocio": "Governance Tree é uma consultoria que nasceu para desmistificar a ideia de que o tema governança corporativa está limitada às grandes empresas. Governança corporativa deve fazer parte da startup e  trazer para empresa, transparência, responsabilidade corporativa, equidade e prestação de contas para os sócios e investidores."
    },
    {
        "Participante": "Isabela Carvalho Melo de Oliveira",
        "nomeNegocio": "Hands On Marketing",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Aline Saito",
        "estagio": "Ideia",
        "eMail": "mkt.handson@gmail.com\r\n",
        "celular": "11996741812",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/isabelamelodeoliveira/",
        "instagramPessoal": "Não localizado",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Imagine uma plataforma onde a economia gira em torno da generosidade, quanto mais você dá, mais você recebe. Funciona como um grande mercado de escambo, onde as pessoas podem consumir produtos e serviços por meio de créditos gerados com uma prestação de serviços ou entrega de produtos. Ainda não concluímos como seria gerado o primeiro crédito (se por compra ou doação do produto/serviço), mas a partir desse primeiro crédito, a pessoa está apta a consumir na plataforma, bem como oferecer os seus produtos e serviços."
    },
    {
        "Participante": "Andrezza Aguiar Rodrigues",
        "nomeNegocio": "HerMoney",
        "checkPonit_1": "OK",
        "Mentora": "Juliane Devaux",
        "estagio": "Lançado com tração e clientes",
        "eMail": "andrezza@hermoney.com.br",
        "celular": "8589111792",
        "cidadeEstado": "Fortaleza - CE",
        "linkedin": "https://www.linkedin.com/in/andrezza-rodrigues-43a8b8152/",
        "instagramPessoal": "Não localizado",
        "siteDaEmpresa": "https://www.hermoney.com.br/",
        "redesSociaisEmpresa": "https://www.instagram.com/hermoneybr/",
        "segmentoDaEmpresa": "Financeiro",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "A HerMoney é um BPO financeiro voltado para mulheres empreendedoras que, por meio da tecnologia, faz todo o financeiro da empresa de uma forma totalmente virtual e automática."
    },
    {
        "Participante": "Beatriz Furtado",
        "nomeNegocio": "HerMoney",
        "checkPonit_1": "OK",
        "Mentora": "Juliane Devaux",
        "estagio": "Lançado com tração e clientes",
        "eMail": "beatriz@hermoney.com.br",
        "celular": "8581808884",
        "cidadeEstado": "Fortaleza - CE",
        "linkedin": "http://linkedin.com/in/anabfurtado",
        "instagramPessoal": "https://www.instagram.com/anabfurtado/",
        "siteDaEmpresa": "https://allmylinks.com/hermoneybr",
        "redesSociaisEmpresa": "https://www.instagram.com/hermoneybr/",
        "segmentoDaEmpresa": "Financeiro",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "A HerMoney é um BPO financeiro voltado para mulheres empreendedoras que, por meio da tecnologia, faz todo o financeiro da empresa de uma forma totalmente virtual e automática."
    },
    {
        "Participante": "Juliana Hemerly Silva",
        "nomeNegocio": "Ikki",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Aline Saito",
        "estagio": "Protótipo/Versão beta",
        "eMail": "juli@ikki.vc",
        "celular": "22997844636",
        "cidadeEstado": "Búzios - RJ",
        "linkedin": "https://www.linkedin.com/in/juliana-hemerly-a35aa012/",
        "instagramPessoal": "https://www.instagram.com/julihemerly/",
        "siteDaEmpresa": "www.ikki.vc",
        "redesSociaisEmpresa": "https://www.instagram.com/ikkivc/",
        "segmentoDaEmpresa": "Educação",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "A Ikki é uma empresa de planos educacionais extra curriculares.Atuamos através de uma rede de parceiros credenciados espalhados por todo Brasil. Através de feedbacks bilaterais 360 e de um sistema próprio de ensino descentralizado baseado em design thinking,buscamos captar o que faz os olhos de cada criança brilhar.Quando encontramos talentos nascendo em qualquer área conectamos com nossos parceiros do clube de talentos ikki :um clube de grandes players de várias áreas que ajudarão na mentoria e direcionamento deste talentos.Todo final de ano os Ikkers apresentam todas suas descobertas no IKKi day: um dia de celebração a diferença .Nosso foco é que nenhum talento se perca e que cada criança ouse ser ela mesma e compartilhar sua autenticidade com o mundo"
    },
    {
        "Participante": "Marcela Costa Simões",
        "nomeNegocio": "KiwKiw",
        "checkPonit_1": "OK",
        "Mentora": "Jaqueline Lamente",
        "estagio": "Lançado com tração e clientes",
        "eMail": "marcelasimoes@kiwkiw.com.br",
        "celular": "11982041277",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/marcela-sim%C3%B5es-4967311b7/",
        "instagramPessoal": "https://www.instagram.com/marcela.csimoes/",
        "siteDaEmpresa": "www.kiwkiw.com.br",
        "redesSociaisEmpresa": "https://www.instagram.com/kiwkiwbrasil/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "O KiwKiw é um sistema de gestão para bares, restaurantes e festas, que tem como objetivo trazer mais agilidade no atendimentos dos clientes e transformar a experiência dos consumidores, que podem realizar a comprar de qualquer item do cardápio em apenas 04 cliques. "
    },
    {
        "Participante": "Brunna Ruzzon de Souza",
        "nomeNegocio": "Lab Law ",
        "checkPonit_1": "OK",
        "Mentora": "Camilla Barbosa",
        "estagio": "Ideia",
        "eMail": "brunnaruzzons@gmail.com",
        "celular": "18997031401",
        "cidadeEstado": "Paranavaí - PR",
        "linkedin": "https://br.linkedin.com/in/brunna-ruzzon-035855169",
        "instagramPessoal": "https://www.instagram.com/brunnaruzzon/",
        "siteDaEmpresa": "https://instagram.com/lablawfirm?igshid=ds7fk5fzxs5k",
        "redesSociaisEmpresa": "https://www.instagram.com/lablawfirm/",
        "segmentoDaEmpresa": "Educação",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Somos uma plataforma Saas que busca democratizar o acesso ao conhecimento jurídico, através de um verdadeiro passo a passo para o empreendedor seguir,com vídeos, e-books, check lists, bem práticos e sem \"juridiquês\". Na era da informação, ter acesso às informações jurídicas verdadeiras e  realmente necessárias é um grande diferencial para um gestor! "
    },
    {
        "Participante": "Marina Franciulli Santos Xavier",
        "nomeNegocio": "Vent.Hub",
        "checkPonit_1": "OK",
        "Mentora": "Taina Paina",
        "estagio": "Ideia",
        "eMail": "marina@mazzicomunica.com.br",
        "celular": "11982039903",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/marinafranciulli/",
        "instagramPessoal": "https://www.instagram.com/mafranciulli/",
        "siteDaEmpresa": "www.mazzicomunica.com.br",
        "redesSociaisEmpresa": "https://www.facebook.com/mazzicomunica",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Plataforma que automatiza a análise de estoque para direcionar ações de promoção de acordo com a sua produção, conectando o seu negócio aos principais canais de divulgação, otimizando recursos e possibilitando mais vendas."
    },
    {
        "Participante": "Ricardo Moreira Xavier",
        "nomeNegocio": "Vent.Hub",
        "checkPonit_1": "OK",
        "Mentora": "Tania Paina",
        "estagio": "Ideia",
        "eMail": "ricardo@mazzicomunica.com.br",
        "celular": "11964310372",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/ricardo-moreira-xavier-7222b897/",
        "instagramPessoal": "https://www.instagram.com/ricardomoreiraxavier/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Plataforma que automatiza a análise de estoque para direcionar ações de promoção de acordo com a sua produção, conectando o seu negócio aos principais canais de divulgação, otimizando recursos e possibilitando mais vendas."
    },
    {
        "Participante": "Andrea Maia Brayer",
        "nomeNegocio": "Mediar360",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Taciana Mello",
        "estagio": "Protótipo/Versão beta",
        "eMail": "andrea.maia47@gmail.com",
        "celular": "21987783698",
        "cidadeEstado": "Rio de Janeiro - RJ",
        "linkedin": "https://www.linkedin.com/in/andrea-maia-695733/",
        "instagramPessoal": "https://www.instagram.com/andreamaia/",
        "siteDaEmpresa": "www.mediar360.com.br",
        "redesSociaisEmpresa": "https://www.instagram.com/mediar360/",
        "segmentoDaEmpresa": "Varejo em geral",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Plataforma inteligente de automação de negociação e mediação, visando a resolução de conflitos jurídicos de empresas que lidam com consumo em massa. Nosso propósito é revolucionar a gestão de conflitos de massa no Brasil, contribuindo com a melhoria das organizações e, consequentemente, do país."
    },
    {
        "Participante": "Iris Vieira Iasbec",
        "nomeNegocio": "Meu Primeiro Alecrim",
        "checkPonit_1": "OK",
        "Mentora": "Tania Paina",
        "estagio": "Lançado com tração e clientes",
        "eMail": "irisyazbek@gmail.com",
        "celular": "11985513388",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "Não possui",
        "instagramPessoal": "https://www.instagram.com/irisyazbek/",
        "siteDaEmpresa": "www.meuprimeiroalecrim.com.br",
        "redesSociaisEmpresa": "https://www.instagram.com/meuprimeiroalecrim/",
        "segmentoDaEmpresa": "Alimentos e bebidas",
        "tipoNegocio": "Produto, hoje sendo remodelado para serviço também.",
        "descricaoNegocio": "Meu Primeiro Alecrim é uma empresa de comidinhas para crianças, com o propósito de alimentar com nutrição, sabor e alegria desde o início do processo de introdução alimentar até sempre. Estendemos os produtos para todas as idades porque acreditamos que comer também é um ato social, crianças que se alimentam em família são mais felizes e se relacionam melhor com os alimentos. O projeto vai além da venda de produtos no e-commerce meuprimeiroalecrim.com.br, a idéia é acolher mães e pais nesse momento tão incrível (mas que pode ser muito sofrido para alguns) que é a IA de um bebê, através de consultoria; cursos e produção de conteúdo informativo (vídeos, ebooks). Nesse momento a empresa está em fase de mudança, com a saída de uma das sócias veio a necessidade de remodelar o negócio e criar novas possibilidades de parcerias e expansões."
    },
    {
        "Participante": "Thereza Cristina Bandoli Legg",
        "nomeNegocio": "MyHelathLib",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Gabriela Serpa",
        "estagio": "Ideia",
        "eMail": "tcbandolilegg.b2mamy@gmail.com",
        "celular": "22988399390",
        "cidadeEstado": "Ouro Branco - MG",
        "linkedin": "https://www.linkedin.com/in/thereza-cristina-bandoli-legg-244a8924/",
        "instagramPessoal": "https://www.instagram.com/tcbandolilegg/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Saúde e bem-estar",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Hoje em dia, somos reféns de nossos prontuários médicos.  É extremamente difícil armazenar e/ou acompanhar todos os registros médicos que possuímos, e isso fica mais difícil, pois necessitamos cuidar de outras pessoas além de nós mesmo, os cuidados de filhos e/ou ainda de nossos pais, faz com que nosso tempo fique mais  apertado e assim dificultando mais e mais mantermos estes acompanhamentos.   Nossa solução é um aplicativo capaz de permitir o armazenamento de dados médicos e/ou relacionados (tipo sanguíneo, alergias medicamentosas ou alimentar, heranças genéticas), podendo ser utilizado em todas as fases da vida (ao nascer, na primeira infância, adolescência, fase adulta e terceira idade).  O mesmo utilizará tecnologia de inteligência artificial, que ajudará na solicitação de informações básicas como vacinas, testes ao nascimento, exames periódicos, medicações de uso contínuo; para o MVP nosso foco será o pré-natal e primeira infância, pois estes dois estão entrelaçados. O seu roadmap é que em um momento posterior de maturidade uma plataforma e/ou sistema web proporcionará a integração ou até mesmo a substituição de sistemas de atendimento médico em consultórios, clínicas, laboratórios de análise clínicas ou patológicas, hospitais, ou ainda compartilhamento de dados com tele medicina."
    },
    {
        "Participante": "Danielle Falcão",
        "nomeNegocio": "Redesign for all",
        "checkPonit_1": "OK",
        "Mentora": "Giseli Fernandes",
        "estagio": "Oficialmente lançado",
        "eMail": "contato.danifalcao@gmail.com",
        "celular": "11979602744",
        "cidadeEstado": "Rio de Janeiro - RJ",
        "linkedin": "https://www.linkedin.com/in/danifalcao/",
        "instagramPessoal": "https://www.instagram.com/daniellefalcaoo/",
        "siteDaEmpresa": "https://www.instagram.com/redesignforall/",
        "redesSociaisEmpresa": "http://www.redesignforall.com/",
        "segmentoDaEmpresa": "Educação",
        "tipoNegocio": "Serviço e comunidade",
        "descricaoNegocio": "Desenvolvemos um programa de capacitação com olhar do design inclusivo e acessibilidade. Lideramos a primeira comunidade de inclusão de pessoas com deficiência no mercado de tecnologia com o negócio social chamado Deficiência Tech."
    },
    {
        "Participante": "Tania Szejnfeld Mann",
        "nomeNegocio": "Sapatímetro",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Itali Colini",
        "estagio": "Ideia",
        "eMail": "tszejnfeld@gmail.com",
        "celular": "11982499918",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/tania-szejnfeld-mann-md-phd-0202133a/",
        "instagramPessoal": "https://www.instagram.com/taniasmann/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "Não possui ainda",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Um aplicativo que vai funcionar como um provador virtual de calçados"
    },
    {
        "Participante": "Solange Soares de Aguiar Silva",
        "nomeNegocio": "Sistechood",
        "checkPonit_1": "OK",
        "Mentora": "Marina Vaz",
        "estagio": "Ideia",
        "eMail": "solangesas@gmail.com",
        "celular": "12992167384",
        "cidadeEstado": "Ubatuba - SP",
        "linkedin": "https://www.linkedin.com/in/solangesas/",
        "instagramPessoal": "https://www.instagram.com/solangetech/",
        "siteDaEmpresa": "https://www.instagram.com/sistechood/",
        "redesSociaisEmpresa": "https://www.facebook.com/sistechood/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Framework para levantar os requisitos funcionais (seguindo a metodologia ágil seriam os épicos do sistema, ou basicamente o que o sistema faz) e os requisitos não-funcionais, que seriam as necessidades tecnológicas, por exemplo, precisa de um banco de dados, requisitos de segurança, tem necessidade de inteligência artificial, etc. de uma ideia de negócio com base tecnológica."
    },
    {
        "Participante": "Silvia Loge Sorroche Berlinck ",
        "nomeNegocio": "Sorriso Sustentável ",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Giseli Fernandes",
        "estagio": "Oficialmente lançado",
        "eMail": "silviaberlinck@gmail.com",
        "celular": "11976201525",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/silvia-berlinck-b5814832/",
        "instagramPessoal": "https://www.instagram.com/silviaberlinck/",
        "siteDaEmpresa": "www.sorrisosustentavel.eco.br",
        "redesSociaisEmpresa": "https://www.instagram.com/sorrisosustentavel/",
        "segmentoDaEmpresa": "Educação",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Com o objetivo de transformar ambientes em locais saudáveis, seguros e sustentáveis, a empresa prioriza a preservação e regeneração do Meio Ambiente,  a promoção da saúde ambiental e o crescimento sustentável das instituições. Nossa visão é ser referência em ações socioambientais na busca de soluções para o gerenciamento de resíduos, educação ambiental e desenvolvimento de projetos e campanhas em parcerias com instituições públicas e privadas. Proposições de valor: disseminar boas práticas de simples execução para que as pessoas se tornem autônomas em executar ações em prol da sustentabilidade; inovação; saúde ambiental; manutenção da vida sobre a Terra; regeneração do Meio Ambiente; qualidade de vida."
    },
    {
        "Participante": "Lidia Duarte Cabral",
        "nomeNegocio": "Tech4Sex",
        "mentoriaPerformance": "Pendente",
        "checkPonit_1": "OK",
        "Mentora": "Taciana Mello",
        "estagio": "Ideia",
        "eMail": "lidiacabral@gmail.com",
        "celular": "11990007007",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/lidia-cabral-68360620/",
        "instagramPessoal": "https://www.instagram.com/lidiacabral/",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/tech4sex/",
        "segmentoDaEmpresa": "Tecnologia",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Tech4Sex é uma plataforma que tem como propósito aplicar as mais recentes tecnologias e metodologias para redefinir e inovar nas abordagens de soluções para melhoria da sexualidade humana. Queremos desenvolver um novo conceito de produtos, serviços e modelos de negócio focados em SEXTECH através da colaboração de especialistas de diferentes áreas como tecnologia, design, engenharia, saúde e bem-estar sexual. "
    },
    {
        "Participante": "Pâmela González Machado",
        "nomeNegocio": "TSER",
        "mentoriaPerformance": "-",
        "checkPonit_1": "-",
        "Mentora": "-",
        "estagio": "Lançado com tração e clientes",
        "eMail": "pamela@rafabrites.com.br ",
        "celular": "11950602306",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/pamelasgonzalez/",
        "instagramPessoal": "Não localizado",
        "siteDaEmpresa": "Não possui ainda",
        "redesSociaisEmpresa": "https://www.instagram.com/tser.rafabrites/",
        "segmentoDaEmpresa": "Educação",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "O TSER é um projeto multiplataforma de cursos de educação baseado em desenvolvimento pessoal. Através de uma comunicação empática, buscamos propiciar o autoconhecimento e o encontro de mulheres que querem, em comunidade, recuperar sua identidade, independência e autoestima."
    },
    {
        "Participante": "Karina Lemos de Sousa",
        "nomeNegocio": "ÚNIKA",
        "mentoriaPerformance": "Pendente",
        "checkPonit_1": "OK",
        "Mentora": "Cecilia Gomes",
        "estagio": "Lançado com tração e clientes",
        "eMail": "karina@unikagestao.com",
        "celular": "11983012021",
        "cidadeEstado": "São Paulo - SP",
        "linkedin": "https://www.linkedin.com/in/karinalemos/",
        "instagramPessoal": "https://www.instagram.com/lemoskarina/",
        "siteDaEmpresa": "http://www.unikagestao.com/",
        "redesSociaisEmpresa": "https://www.instagram.com/unikagestao/",
        "segmentoDaEmpresa": "Tecnologia",
        "descricaoNegocio": "Vistorias e Facilitadora de Tarefas para o Mercado Imobiliário! Garantimos segurança e agilidade para a entrega do seu empreendimento."
    },
    {
        "Participante": "Ivonete Guarino da Silva Ramos",
        "nomeNegocio": "Vô Contigo ",
        "mentoriaPerformance": "OK",
        "checkPonit_1": "OK",
        "Mentora": "Camilla Barbosa",
        "estagio": "Protótipo/Versão beta",
        "eMail": "ivonete.guarino@gmail.com",
        "celular": "65922091976",
        "cidadeEstado": "Várzea Grande - MT",
        "linkedin": "https://www.linkedin.com/in/ivoneteguarino/",
        "instagramPessoal": "https://www.instagram.com/ivoneteguarino/",
        "siteDaEmpresa": "https://www.instagram.com/vo.contigo/",
        "redesSociaisEmpresa": "https://www.instagram.com/vo.contigo/",
        "segmentoDaEmpresa": "Mobilidade urbana",
        "tipoNegocio": "Serviços",
        "descricaoNegocio": "Temos como linda e desafiadora missão contribuir com a inclusão dos idosos na sociedade, proporcionando a eles a liberdade de ir e vir com a segurança, a autonomia e o carinho que eles merecem. Faremos isso por meio de transporte qualificado para nossos idosos, com carros adaptados e profissionais criteriosamente selecionados e treinados para garantir ao idoso o atendimento humanizado que ele merece. Para os que desejarem, haverá também a opção de um Concierge, que é um profissional habilitado para acompanhar o idoso no desempenhar suas atividades de rotina, restaurando-lhe assim certa medida de liberdade e autonomia!"
    }
]
